### PR TITLE
Fix missing thumbnail in public room

### LINKED ISSUE #265: Image preview aren't shown if the event don't include thumbnail
Some client don't include thumbnail (for example Tchap Android v2).
In that case an image sent with Tchap Android v2 will not shown an thumbnail. 

Edit from Estelle : the bug only happens in public forums

In that case :
- The first image was sent with Tchap Web -> it's working, the thumbnail is showned
- The second image was sent with Tchap Android 2 -> it's not working
image

### PR DESCRIPTION
**Pull request by jdauphant**
matrix-react-sdk https://github.com/tchapgouv/matrix-react-sdk/pull/411

fix #265 

image
Before -> After

### CODE REVIEW

**Comment by jdauphant** [comment]
An another solution could be : 
https://github.com/tchapgouv/matrix-react-sdk/blob/64f44cd4e46ac47a3cb2197ceaabf1459c8308d3/src/components/views/messages/MImageBody.js#L431
`this.props.matrixClient.mxcUrlToHttp(thumbUrl, 800, 600, 'scale', false);`

**Comment by estellecomment** [comment]
I don't really know when this problem is happening, so it's hard for me to check if it's fixed. The issue (https://github.com/tchapgouv/tchap-web/issues/265) is not really detailed. Maybe @JDixmier knows more about this and can test ?

**Comment by jdauphant** [comment]
@estellecomment I have put more description : https://github.com/tchapgouv/tchap-web/issues/265 
To test it, send an image from Tchap Android and check the result on Tchap Web v2 (you can have dev apk here : https://github.com/tchapgouv/tchap-android/actions/runs/2577587332 )

**Comment by estellecomment** [comment]
I don't see the bug happening.
 - with the apk you linked (2.3.2_dev), with the dev backend, and the latest tchap-web#develop with the dev backend
 - with the current android apk in prod (2.3.1) and the current tchap-web in prod
 
 So I don't know if it's fixed...

**Comment by estellecomment** [comment]
@JDixmier and myself can now confirm it works !!

**Pull request merged**
